
import { ButtonArrowLeft } from '@/Components/ButtonArrowLeft'
import { ButtonArrowRigth } from '@/Components/ButtonArrowRight'
import { ContentImages } from '@/Components/ContentImage'
import { ContentImageArrow } from '@/Components/ContentImageArrow'
import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>Background Slider Nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <ContentImageArrow
    
    img={[
      "/images/img1.jpeg",
      "/images/img2.jpeg",
      "/images/img3.jpeg",
      "/images/img4.jpeg",
      "/images/img5.jpeg",
      "/images/img6.jpeg",    
    ]}
    
    
    />
      
      
      

    </>
    
    
  )
}
